### ISSUE TITLE
Criação do Roadmap planejado do projeto

### ISSUE THREAD

**Issue by Gxaite** [ResidenciaTICBrisa/T2G2-Chatbot-Participacao-Social#31]
## Descrição

Esta issue tem como objetivo a criação de um roadmap de desenvolvimento planejado, que será seguido pelo grupo. O roadmap fornecerá uma visão clara das etapas e metas a serem alcançadas durante o desenvolvimento do projeto, ajudando a orientar e alinhar os esforços da equipe. 
## Tarefas
- [x] Divisão das etapas 
- [x] Atomização das tarefas
- [x] Elaborar uma ordem lógica de desenvolvimento
- [x] Pensar nas possibilidades de tecnologia

## Testes / Avaliação
- [ ] Validar com o cliente o Roadmap estabelecido

**Comment by GZaranza** [comment]
A criação do roadmap n foi possivel finalizar na sprint 2 por causa do escopo que ainda n tinha sido definido. Essa issue será movida para outra sprint

**Comment by Gxaite** [comment]
O RoadMap foi criado pensando na aprsentação tanto para o gestor da Brisa quanto para o cliente final. Segue o link para o projeto do canva com os dois slides separados.
https://www.canva.com/design/DAGAEe9BNYs/omkuor2sNPUKJsq6tBSF7A/edit
