### ISSUE TITLE
Atualizar roadmap 

### ISSUE THREAD

**Issue by Gxaite** [ResidenciaTICBrisa/T2G2-Chatbot-Participacao-Social#87]
# Atualizar o Roadmap

## Descrição
Precisamos atualizar o roadmap do projeto para refletir os objetivos e marcos mais recentes. Isso ajudará a equipe e a comunidade a entender o progresso e as próximas etapas do projeto.

## Tarefas
- [x] Revisar os marcos e objetivos atuais do projeto
- [x] Adicionar novos marcos e objetivos conforme necessário
- [x] Atualizar as datas estimadas de conclusão para cada etapa
- [x] Garantir que o roadmap esteja visualmente claro e acessível

**Comment by Gxaite** [comment]
O roadmap foi revisado e ajustado para atender às expectativas atuais do projeto.
